{% set version = "0.3.38" %}

package:
  name: r-bcbiornaseq
  version: "{{ version }}"

source:
  url: "https://github.com/hbc/bcbioRNASeq/archive/v{{ version }}.tar.gz"
  sha256: c5e87ee49b13228bea19e4e56f3d2d670e88af3691efbf51bd84d90948fe3b96

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
      # Depends:
    - r-base
    - bioconductor-summarizedexperiment >=1.18
    - r-basejump >=0.13.1
      # Imports:
    - bioconductor-biocgenerics
    - bioconductor-deseq2 >=1.28
    - bioconductor-edger >=3.30
    - bioconductor-s4vectors
    - bioconductor-tximport >=1.16
    - r-acidgenerics >=0.4.0
    - r-acidplots >=0.3.0
    - r-bcbiobase >=0.6.14
    - r-cli >=2.0
    - r-cowplot >=1.0
    - r-ggplot2 >=3.3
    - r-goalie >=0.4.9
    - r-rlang >=0.4
    - r-scales >=1.1
    - r-sessioninfo >=1.1
      # Suggests:
    - bioconductor-biocstyle
    - bioconductor-clusterprofiler
    - bioconductor-degreport
    - r-deseqanalysis
    - bioconductor-dose
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-pathview
    - bioconductor-rhdf5
    - bioconductor-vsn
    - r-hexbin
    - r-knitr
    - r-rmarkdown
    - r-roxygen2
    - r-tidyverse
    - r-viridis
  run:
    - r-base
    - bioconductor-summarizedexperiment >=1.18
    - r-basejump >=0.13.1
      # Imports:
    - bioconductor-biocgenerics
    - bioconductor-deseq2 >=1.28
    - bioconductor-edger >=3.30
    - bioconductor-s4vectors
    - bioconductor-tximport >=1.16
    - r-acidgenerics >=0.4.0
    - r-acidplots >=0.3.0
    - r-bcbiobase >=0.6.14
    - r-cli >=2.0
    - r-cowplot >=1.0
    - r-ggplot2 >=3.3
    - r-goalie >=0.4.9
    - r-rlang >=0.4
    - r-scales >=1.1
    - r-sessioninfo >=1.1
      # Suggests:
    - bioconductor-biocstyle
    - bioconductor-clusterprofiler
    - bioconductor-degreport
    - r-deseqanalysis
    - bioconductor-dose
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-pathview
    - bioconductor-rhdf5
    - bioconductor-vsn
    - r-hexbin
    - r-knitr
    - r-rmarkdown
    - r-roxygen2
    - r-tidyverse
    - r-viridis

test:
  commands:
    - $R -e "library('bcbioRNASeq')"

about:
  home: http://bioinformatics.sph.harvard.edu/bcbioRNASeq/
  dev_url: https://github.com/hbc/bcbioRNASeq
  license: MIT
  license_file: LICENSE
  summary: R package for bcbio RNA-seq analysis.
